/* *
 *
 *  Generating sitemap.xml for the Morningstar connector docs.
 *
 *  URLs mirror docs/llms.txt (base https://www.highcharts.com/docs).
 *  <lastmod> is derived per page from the last git commit that touched the
 *  source markdown file, so it stays honest and drives incremental
 *  re-indexing. Do not hand-write dates - re-run this script instead:
 *
 *      npx ts-node tools/sitemap
 *
 *  (c) Highsoft AS
 *
 * */


/* eslint-disable no-console */


/* *
 *
 *  Imports
 *
 * */


import { execFileSync } from 'node:child_process';
import * as FS from 'node:fs';
import * as Path from 'node:path';


/* *
 *
 *  Constants
 *
 * */


const BASE_URL = 'https://www.highcharts.com/docs/morningstar';

const DOCS_ROOT = Path.join('docs', 'connectors');

const OUTPUT = Path.join('docs', 'sitemap.xml');


/**
 * Page groups. Each `slug` is appended to BASE_URL for the `<loc>` and, unless
 * an explicit `file` is given, maps to `docs/connectors/morningstar/<slug>.md`.
 * `priority` is a soft ranking hint: DWS pages are raised to reflect the
 * "prefer DWS for Morningstar queries" steer, others default lower.
 */
const GROUPS: Array<{
    title: string;
    priority: string;
    pages: Array<{ slug: string; file?: string }>;
}> = [
    {
        title: 'Getting started',
        priority: '0.9',
        pages: [
            // Overview lives at docs/connectors/morningstar.md, but publishes
            // under /morningstar/morningstar.
            { slug: 'morningstar', file: 'morningstar.md' }
        ]
    },
    {
        title: 'Direct Web Services (DWS)',
        priority: '1.0',
        pages: [
            { slug: 'dws/investments-details-connector' },
            { slug: 'dws/time-series-connector' },
            { slug: 'dws/asset-allocation-breakdown' },
            { slug: 'dws/country-and-regional-exposure-breakdown' },
            { slug: 'dws/equity-style-box' },
            { slug: 'dws/equity-sectors-breakdown' },
            { slug: 'dws/equity-residual-risk' },
            { slug: 'dws/equity-aggregates-residual-risk' },
            { slug: 'dws/fixed-income-sectors-breakdown' },
            { slug: 'dws/prospectus-fees' }
        ]
    },
    {
        title: 'Connectors',
        priority: '0.8',
        pages: [
            { slug: 'goal-analysis' },
            { slug: 'hypo-performance' },
            { slug: 'performance' },
            { slug: 'risk-score' },
            { slug: 'security-compare' },
            { slug: 'security-details' },
            { slug: 'x-ray' }
        ]
    },
    {
        title: 'Screeners',
        priority: '0.8',
        pages: [
            { slug: 'screeners/screener' },
            { slug: 'screeners/investment-screener' },
            { slug: 'screeners/find-similar-screener' }
        ]
    },
    {
        title: 'Time Series',
        priority: '0.8',
        pages: [
            { slug: 'time-series/time-series' },
            { slug: 'time-series/price' },
            { slug: 'time-series/ohlcv' },
            { slug: 'time-series/return' },
            { slug: 'time-series/cumulative-return' },
            { slug: 'time-series/rolling-return' },
            { slug: 'time-series/growth' },
            { slug: 'time-series/dividend' },
            { slug: 'time-series/rating' }
        ]
    }
];


/* *
 *
 *  Functions
 *
 * */


/**
 * Resolves the source markdown file for a page slug.
 *
 * @param page
 * Page entry to resolve.
 *
 * @param page.slug
 * URL slug appended to the base URL.
 *
 * @param page.file
 * Optional explicit source file, relative to `docs/connectors`.
 *
 * @return
 * Repository-relative path to the source markdown file.
 */
function sourceFile (
    page: { slug: string; file?: string }
): string {
    return Path.join(
        DOCS_ROOT,
        page.file ?? Path.join('morningstar', `${page.slug}.md`)
    );
}


/**
 * Returns the last-modified date (YYYY-MM-DD) of a file from git, falling back
 * to the filesystem mtime for files not yet committed.
 *
 * @param file
 * Repository-relative path to the file to inspect.
 *
 * @return
 * Last-modified date as a `YYYY-MM-DD` string.
 */
function lastModified (
    file: string
): string {
    try {
        const out = execFileSync(
            'git',
            ['log', '-1', '--format=%cs', '--', file],
            { encoding: 'utf8' }
        ).trim();

        if (out) {
            return out;
        }
    } catch {
        // fall through to mtime
    }

    return FS.statSync(file).mtime.toISOString().slice(0, 10);
}


function generate (): string {
    const lines: string[] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!--',
        '  Sitemap for the Morningstar connector docs.',
        '  Generated by tools/sitemap.ts - do not edit by hand.',
        '  URLs mirror docs/llms.txt; <lastmod> comes from git per page.',
        '-->',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
    ];

    for (const group of GROUPS) {
        lines.push('', `  <!-- ${group.title} -->`);

        for (const page of group.pages) {
            const file = sourceFile(page);

            if (!FS.existsSync(file)) {
                throw new Error(`Missing source doc for sitemap: ${file}`);
            }

            lines.push(
                '  <url>',
                `    <loc>${BASE_URL}/${page.slug}</loc>`,
                `    <lastmod>${lastModified(file)}</lastmod>`,
                `    <priority>${group.priority}</priority>`,
                '  </url>'
            );
        }
    }

    lines.push('', '</urlset>', '');

    return lines.join('\n');
}


/* *
 *
 *  Runtime
 *
 * */


const xml = generate();

FS.writeFileSync(OUTPUT, xml);

const count = (xml.match(/<url>/gu) ?? []).length;

console.log(`Wrote ${OUTPUT} with ${count} URLs.`);
