/* *
 *
 *  Generates docs/sitemap.xml. Run with `npm run sitemap`.
 *
 *  Pages are read from the docs folders, so adding a doc never means editing
 *  this script. <lastmod> is derived per page from git, so it stays honest -
 *  do not hand-write dates.
 *
 *  (c) Highsoft AS
 *
 *  Authors:
 *  - Andrzej Bułeczka
 *
 * */


/* *
 *
 *  Imports
 *
 * */


import { execFileSync } from 'node:child_process';
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, sep } from 'node:path';


/* *
 *
 *  Declarations
 *
 * */


interface Section {
    heading: string;
    /** Single source files, relative to `DOCS_ROOT`. */
    files?: string[];
    /** Folders whose direct markdown children belong to the section. */
    dirs?: string[];
}


/* *
 *
 *  Constants
 *
 * */


const BASE_URL = 'https://www.highcharts.com/docs/morningstar';

const DOCS_ROOT = join('docs', 'connectors');

const OUTPUT = join('docs', 'sitemap.xml');


/**
 * Section layout. Only the headings and their order live here; the pages are
 * read from the folders, so adding a doc never means touching this list.
 */
const LAYOUT: Section[] = [
    { heading: 'Getting started', files: ['morningstar.md'] },
    { heading: 'Direct Web Services (DWS)', dirs: ['morningstar/dws'] },
    {
        heading: 'Enterprise Components',
        dirs: [
            'morningstar',
            'morningstar/screeners',
            'morningstar/time-series'
        ]
    }
];


/* *
 *
 *  Functions
 *
 * */


/**
 * Direct markdown children of a folder.
 *
 * @param dir
 * Folder relative to `DOCS_ROOT`.
 *
 * @return
 * Paths relative to `DOCS_ROOT`.
 */
function dirDocs (
    dir: string
): string[] {
    return readdirSync(join(DOCS_ROOT, dir), { withFileTypes: true })
        .filter(entry => entry.isFile() && entry.name.endsWith('.md'))
        .map(entry => join(dir, entry.name))
        .sort();
}


/**
 * Public URL of a doc.
 *
 * @param rel
 * Path relative to `DOCS_ROOT`.
 *
 * @return
 * Absolute page URL.
 */
function pageUrl (
    rel: string
): string {
    const slug = rel
        .split(sep).join('/')
        .replace(/\.md$/u, '')
        .replace(/^morningstar\//u, '');

    return `${BASE_URL}/${slug}`;
}


/**
 * Whether a file differs from HEAD (staged, unstaged or untracked), and so has
 * no up-to-date commit date yet.
 *
 * @param file
 * File to inspect.
 *
 * @return
 * `true` when the file differs from HEAD.
 */
function isModified (
    file: string
): boolean {
    try {
        execFileSync('git', ['diff', '--quiet', 'HEAD', '--', file]);
        return false;
    } catch {
        return true;
    }
}


/**
 * Last-modified date (`YYYY-MM-DD`) of a file. Unchanged files use their git
 * commit date, stable across checkouts; a file changed in the working tree
 * uses its filesystem mtime, so a pre-commit regeneration reflects the change.
 *
 * @param file
 * File to inspect.
 *
 * @return
 * Date as a `YYYY-MM-DD` string.
 */
function lastModified (
    file: string
): string {
    if (!isModified(file)) {
        const date = execFileSync(
            'git',
            ['log', '-1', '--format=%cs', '--', file],
            { encoding: 'utf8' }
        ).trim();

        if (date) {
            return date;
        }
    }

    return statSync(file).mtime.toISOString().slice(0, 10);
}


/**
 * Resolves the layout into sections of doc paths, failing when a doc sits in
 * a folder no section covers, so a new page is never silently dropped.
 *
 * @return
 * Sections with their doc paths, relative to `DOCS_ROOT`.
 */
function sections (): Array<{ heading: string; docs: string[] }> {
    const resolved = LAYOUT.map(section => ({
        heading: section.heading,
        docs: [
            ...section.files || [],
            ...(section.dirs || []).flatMap(dirDocs)
        ]
    }));

    const covered = new Set(resolved.flatMap(section => section.docs));
    const missing = readdirSync(DOCS_ROOT, { encoding: 'utf8', recursive: true })
        .filter(rel => rel.endsWith('.md') && !covered.has(rel));

    if (missing.length) {
        throw new Error(
            'Docs not covered by any sitemap section:\n  ' +
            missing.map(rel => join(DOCS_ROOT, rel)).join('\n  ')
        );
    }

    return resolved;
}


/**
 * Renders the complete sitemap.
 *
 * @return
 * The sitemap XML.
 */
function generate (): string {
    return [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by tools/sitemap.ts - do not edit by hand. -->',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        ...sections().flatMap(section => [
            '', `  <!-- ${section.heading} -->`,
            ...section.docs.flatMap(rel => [
                '  <url>',
                `    <loc>${pageUrl(rel)}</loc>`,
                `    <lastmod>${lastModified(join(DOCS_ROOT, rel))}</lastmod>`,
                '  </url>'
            ])
        ]),
        '',
        '</urlset>',
        ''
    ].join('\n');
}


/* *
 *
 *  Runtime
 *
 * */


const xml = generate();

writeFileSync(OUTPUT, xml);

process.stdout.write(
    `Wrote ${OUTPUT} with ${(xml.match(/<url>/gu) ?? []).length} URLs.\n`
);
