/* *
 *
 *  Generates docs/sitemap.xml. Run with `npm run sitemap`.
 *
 *  Pages and priorities come from tools/libs/Docs.ts (shared with llms.txt).
 *  <lastmod> is derived per page from git, so it stays honest - do not
 *  hand-write dates.
 *
 *  (c) Highsoft AS
 *
 *  Authors:
 *  - Andrzej Bułeczka
 *
 * */


/* *
 *
 *  Imports
 *
 * */


import { execFileSync } from 'node:child_process';
import { statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { DocsSection } from './libs/Docs';
import { buildSections } from './libs/Docs';


/* *
 *
 *  Constants
 *
 * */


const OUTPUT = join('docs', 'sitemap.xml');


/* *
 *
 *  Functions
 *
 * */


/**
 * Whether a file differs from HEAD (staged, unstaged or untracked), and so has
 * no up-to-date commit date yet.
 *
 * @param file
 * File to inspect.
 *
 * @return
 * `true` when the file differs from HEAD.
 */
function isModified (
    file: string
): boolean {
    try {
        execFileSync('git', ['diff', '--quiet', 'HEAD', '--', file]);
        return false;
    } catch {
        return true;
    }
}


/**
 * Last-modified date (`YYYY-MM-DD`) of a file. Unchanged files use their git
 * commit date, stable across checkouts; a file changed in the working tree
 * uses its filesystem mtime, so a pre-commit regeneration reflects the change.
 *
 * @param file
 * File to inspect.
 *
 * @return
 * Date as a `YYYY-MM-DD` string.
 */
function lastModified (
    file: string
): string {
    if (!isModified(file)) {
        const date = execFileSync(
            'git',
            ['log', '-1', '--format=%cs', '--', file],
            { encoding: 'utf8' }
        ).trim();

        if (date) {
            return date;
        }
    }

    return statSync(file).mtime.toISOString().slice(0, 10);
}


/**
 * `<url>` blocks for every page of a section, at the section's priority.
 *
 * @param section
 * Section to render.
 *
 * @return
 * XML lines for the section.
 */
function sectionEntries (
    section: DocsSection
): string[] {
    const pages = [
        ...section.pages,
        ...section.groups.flatMap(group => group.pages)
    ];

    return [
        '', `  <!-- ${section.heading} -->`,
        ...pages.flatMap(page => [
            '  <url>',
            `    <loc>${page.url}</loc>`,
            `    <lastmod>${lastModified(page.file)}</lastmod>`,
            `    <priority>${section.priority}</priority>`,
            '  </url>'
        ])
    ];
}


function generate (): string {
    return [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by tools/sitemap.ts - do not edit by hand. -->',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        ...buildSections().flatMap(sectionEntries),
        '',
        '</urlset>',
        ''
    ].join('\n');
}


/* *
 *
 *  Runtime
 *
 * */


const xml = generate();

writeFileSync(OUTPUT, xml);

process.stdout.write(
    `Wrote ${OUTPUT} with ${(xml.match(/<url>/gu) ?? []).length} URLs.\n`
);
